import { Task } from "./types";

export function createTask(
  id: string,
  title: string,
  description: string,
  location: string,
  points: number,
  difficulty: "easy" | "medium" | "hard",
  lat: number,
  lng: number,
): Task {
  return {
    id,
    title,
    description,
    points,
    location,
    difficulty,
    coordinates: { lat, lng },
  };
}

export const TASKS_BY_LOCATION: Task[] = [
  createTask(
    "ggp-bison-1",
    "Photo with the Bisons",
    "Take a selfie with the American bison paddock in the background",
    "Bison Paddock",
    25,
    "easy",
    37.7705,
    -122.4923,
  ),
  createTask(
    "ggp-windmill-1",
    "Dutch Windmill Challenge",
    "Do a traditional Dutch dance pose in front of the Dutch Windmill",
    "Dutch Windmill",
    30,
    "medium",
    37.7713,
    -122.5103,
  ),
  createTask(
    "ggp-japanese-1",
    "Tea Garden Meditation",
    "Record a 30-second meditation video at the Japanese Tea Garden entrance",
    "Japanese Tea Garden",
    35,
    "medium",
    37.7701,
    -122.47,
  ),
  createTask(
    "ggp-carousel-1",
    "Carousel Excitement",
    "Capture your best excited face while riding the historic carousel",
    "Koret Children's Quarter",
    20,
    "easy",
    37.7687,
    -122.4569,
  ),
  createTask(
    "ggp-conservatory-1",
    "Botanical Beauty",
    "Take a creative photo showcasing the Conservatory of Flowers architecture",
    "Conservatory of Flowers",
    40,
    "hard",
    37.7735,
    -122.4606,
  ),
  createTask(
    "ggp-haight-1",
    "Hippie Spirit",
    "Strike a peace sign pose near the Haight-Ashbury entrance to the park",
    "Haight Street Entrance",
    15,
    "easy",
    37.7697,
    -122.4545,
  ),
  createTask(
    "pier39-sealions",
    "Sea Lion Impression",
    "Do your best sea lion bark and pose at Pier 39",
    "Pier 39",
    45,
    "medium",
    37.8087,
    -122.4098,
  ),
  createTask(
    "lombard-street",
    "Crookedest Street Photo",
    "Take a creative photo on the famous winding Lombard Street",
    "Lombard Street",
    35,
    "hard",
    37.8021,
    -122.4187,
  ),
];
